In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import scipy
import csv
from scipy.optimize import curve_fit

In [20]:
px = []
i = []

with open('d.dat') as data:
    csv_reader = csv.reader(data, delimiter=' ')

    for line in csv_reader:
        px.append(float(line[0]))
        i.append(float(line[1]))

px = np.array(px)
i = np.array(i)

In [21]:
plt.plot(px,i)
plt.xlabel('Pixels')
plt.ylabel('Relative intensity')
plt.show()

In [22]:
s = 656.279-653.288

In [24]:
np.where(i==max(i))

(array([1101]),)

In [25]:
np.where(i==max(i[:200]))

(array([74]),)

In [26]:
sc = s/(1101-74)

In [27]:
b = 653.279-74*sc

In [28]:
wl = px*sc+b

In [33]:
plt.plot(wl,i)
plt.xlabel('Wavelength (nm)')
plt.ylabel('Relative intensity')
plt.show()

In [31]:
wl[np.where(i==max(i[:1050]))]

array([656.09234567])

In [32]:
sc

0.0029123661148977463